### PR TITLE
Updated HTRVX and updated the zone names and line names with latest p…

### PR DESCRIPTION
**Pull request by PonteIneptique**
Sorry for the wrong message: I updated HTRVX yesterday, and this is now much more documented: https://github.com/HTR-United/HTRVX

I updated the files so that they pass the Segmonto tests !

### CODE REVIEW

**Comment by nickjwhite** [comment]
Thanks for this @PonteIneptique! One of the tests you've added is failing, htrvx/test, can you advise on whether the test should be changed, or the ground truth should be changed, please? A cursory look suggests that it's a bunch of empty zones in the XML that's being complained about.

**Comment by PonteIneptique** [comment]
Hey :)
I just updated the tests as well as added some conversion routine for script so that this dataset is comptabile with other datasets (see the few different Latin script dataset at https://htr-united.github.io/catalog.html ).
It also created badges now with some metrics (number of line, characters, etc.) which I can deactivate easily if you want :)
You can basically have this kind of things in your README.md (same script)

image

**Comment by nickjwhite** [comment]
Thanks again for these patches, I'm super grateful :)

**Comment by PonteIneptique** [comment]
I am super grateful myself for the data you put online ;)

**Pull request merged**
