### PR TITLE
Added Alto Transcription with images in color.

### PR DESCRIPTION
**Pull request by PonteIneptique**
This can be used for training with Kraken.

Other changes:
- Added HTR-United suite of actions to track empty lines and stats in general ( https://htr-united.github.io/ )
  -  HTRVX shows which file is missing transcriptions
- Added HTR-United Catalog file (Added myself as Aligner)
- Added Full Text transcription using each folder text files
- Segmentation is done according to the current state of Segmonto ( https://github.com/SegmOnto/examples )

General informations:
- Some files have empty lines, due to the original transcriptions
- Some files treat & as "et" and some as "&"
- For now, I did not change the transcription, except for clear errors (most surely due to the binarization)
- Added some transcription (specifically rubricated text)
- As Ocropy is not the target anymore, diving into MUFI would be a great things for all the specific characters.

### CODE REVIEW

**Comment by nickjwhite** [comment]
Thanks so much, this looks great! Apologies for not getting to this sooner, we've been very busy working on a new GUI for Tesseract (thanks to a kickstarter).

It's fab to get the training in a form that Kraken is happy with. Does Kraken use the ALTO XML for segmentation nowadays, then?

I'm not clear on what the HTR-United actions do - I haven't used Github actions before. Are they needed for the tools on your side to work with this ground truth? Either way, I'd appreciate a bit more info on what they're doing and why they're useful.

We have some more ground truth now that we will want to add to this repository in a bit (once the GUI work has settled down). Would the actions tools complain if we added those, in the Tesseract/Ocropus friendly format we've used 'til now? And would you be up for adding the Kraken / HTR-United versions in due course?

Relatedly there will be more ground truth repositories added here eventually, let me know if there are things we could do to make them work better for you / others.

Finally, it would be good to update the README to mention all this cool new stuff. I can do that after merging, but if there are specific instructions for using it with Kraken, or specific things you think would be good to mention, feel free to either make changes in an updated pull request, or mention them in a comment here.

I'm happy to merge once I've received answers to these questions, with the minor caveat that I want to understand better what the github actions stuff do before committing to them either way. Thanks again for this, it's great, and I'm so pleased you found and have spent time improving this training!

**Comment by PonteIneptique** [comment]
> It's fab to get the training in a form that Kraken is happy with. Does Kraken use the ALTO XML for segmentation nowadays, then?
Yes, it accepts more traditional XML (PageXML and Alto)

> I'm not clear on what the HTR-United actions do - I haven't used Github actions before. Are they needed for the tools on your side to work with this ground truth? Either way, I'd appreciate a bit more info on what they're doing and why they're useful.

The HTR-United actions are there to do some quality control regarding the segmentation, the textual data or the catalog information:

- `HTRUC` allows for controlling that the htr-united catalog file is parsable and HTR-United compliant. This allows the HTR-United central repository to build a general catalog for everyone's use, see https://github.com/HTR-United/htr-united/blob/master/htr-united.yml. It soon will be able to update some details of the catalog
- `ChocoMufin` controls the characters that are used in the transcription. It can be fed a table to tell which one are accepted, and optionally a converting table to normalize characters for a specific dataset.
- `htrvx` checks the XML schema and the Segmonto ontology's use for segmentation: https://segmonto.github.io/
- `htr-united-metadata-generator` generates metadata, specifically metrics

I just finished an important deadline and I am on my way to update some of these tools so that they are clearer in intent and more useful.

> Would the actions tools complain if we added those, in the Tesseract/Ocropus friendly format we've used 'til now?

The tools I provided are specific to XML ALTO and PAGE XML, they won't bug because of other formats but won't care for them either.

>  And would you be up for adding the Kraken / HTR-United versions in due course?

Yup

> Finally, it would be good to update the README to mention all this cool new stuff. I can do that after merging, but if there are specific instructions for using it with Kraken, or specific things you think would be good to mention, feel free to either make changes in an updated pull request, or mention them in a comment here.

I'll comment if necessary (I am taking care of my little one right now, hence the answer in two steps)

> Relatedly there will be more ground truth repositories added here eventually, let me know if there are things we could do to make them work better for you / others.

I think the main issue I have seen is the `&`/`et` alternance in the ground truth. I think it would be great to use the table from Choco Mufin to advertise which character are part of your set as well. But otherwise, everything is cool ;)

**Comment by nickjwhite** [comment]
Great, thanks so much for the clear explanations, that all sounds great, I've very happily merged them in now. I also added a line to the README to mention the new full page image & ground truth stuff you've added, feel free to suggest changes or additions if you think they're warranted.

One of the 4 github actions failed to complete successfully when I merged, by the way, see https://github.com/rescribe/carolineminuscule-groundtruth/runs/5138724352 - looks like a few XML files where some minLength fields are empty. Not a particular priority for me to fix (and there's always a chance I'd screw something up, given that I'm not experienced with ALTO at all), so please fix this and put in a new pull request at some point if you have the time.

**Comment by PonteIneptique** [comment]
Thanks !
The errors are due to the old HTRUC which did not accept empty lines. I left empty lines where there was text but no transcription. This will change in the next version of HTRUC.

Just FYI, you can have a look at the catalog now (beta): https://htr-united.github.io/catalog.html

**Comment by nickjwhite** [comment]
Ah cool, I wondered whether those errors would be things that you'd be fixing in the HTRUC, good to hear.

The catalog looks fantastic, I'm so pleased you guys are creating it, we've talked several times before about the need for such things! Thanks for all your work putting it together.

**Pull request merged**
